### PR TITLE
use integers instead of numbers

### PR DESCRIPTION
**Pull request by unlessgames**
Converted every instance where an integer was annotated as a number.

### CODE REVIEW

**Comment by emuell** [comment]
Looks great.

Found a few more integers at:

* various renoise.InstrumentMidiOutputProperties fields
* table.count(t) and @class Stat fields in standard.lua

* ObservableXXXList:find and size() in observable.lua
* Indices in ListElementAdded/Removed/Swapped in observable.lua

* Views.View's field width height are actually also integers (just verified this)
* Same for Views.Aligner and Views.Rack's margin and spacing

Let me know if I should take care of them in a second pass or if you want to add them in this PR.

**Comment by unlessgames** [comment]
Thanks, I changed them!

How about 
* timeout ms for sockets
* interval ms for tool timers
* track color blend

**Comment by emuell** [comment]
The ms values are numbers internally, but color blend is an integer indeed. Not sure why, should have been a 0-1 float. But as it's now a 0-100 integer, it should also be documented as one. Thanks!

**Comment by unlessgames** [comment]
Well, the track color blend shows up in the built-in color picker as an int from 0 to 100 as well so I think it's fine that the API mirrors that.

I guess that's it for integers then!

**Comment by emuell** [comment]
Yup. Perfect. Merging this now.

**Pull request merged**
