### PR TITLE
Cleanup class defs

### PR DESCRIPTION
**Pull request by unlessgames**
Does #35 

Also removed bit from standard as it was already defined in bit.lua.

### CODE REVIEW

**Comment by unlessgames** [comment]
To further ease the doc generation, it would be nice if we could tag `---@class` on the global objects like 

```lua
---@class renoise
renoise = {}
```

If this is present the JSON export already collects all functions and fields set on the these things, otherwise it needs to be collected manually everywhere just because of these outliers.

This affects `renoise` `Midi` `Osc` `Socket` and possibly something else.

**Comment by unlessgames** [comment]
We should consider moving the operator descriptions inside the class descriptions, otherwise they won't show up in the export.

**Comment by unlessgames** [comment]
What is the purpose of `local Aligner = {}` in `views/aligner.lua` and all the other view files?

**Comment by emuell** [comment]
I'm now getting warnings from LuaLS for all removed definitions, where constants, enums are defined:

e.g.

*Missing required fields in type `renoise.DeviceParameter`:...*

```lua
---### constants

---@enum renoise.DeviceParameter.Polarity
renoise.DeviceParameter = {
  POLARITY_UNIPOLAR = 1,
  POLARITY_BIPOLAR = 2
}
```

Adding a `renoise.DeviceParameter = { }` on top of the file, without the `@class renoise.DeviceParameter` fixes that. 
Is that causing troubles in the JSON output?

> To further ease the doc generation, it would be nice if we could tag ---@class on the global objects like

Sure. This should not break something.

> What is the purpose of local Aligner = {} in views/aligner.lua and all the other view files?

It's the new way of hiding the class instance from the globals. Similar to what you've done with `local ViewBuilderInstance = {}`
I had planed to do change this everywhere, only keeping the enums, consts in the global `renoise.SomeClass = {}` definition.

**Comment by unlessgames** [comment]
Right... I had my definitions loaded from elsewhere and didn't realize this. 

> Adding a `renoise.DeviceParameter = { }` on top of the file, without the `@class renoise.DeviceParameter` fixes that.
> Is that causing troubles in the JSON output?

I progressed a bit more since then and it's not that much trouble actually either way.

But without the `@class` annotation, those globals will only have the enum and not anything else that was added to the class. This is actually something we might want in cases where we need to separate the instance methods from global fields and methods, but not always.

**Pull request closed without merging**
